<?php
        require 'templates/pag/header.phtml';        
        ?>    
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="text-center">IDProducto</th>
                    <th class="text-center">IDCategoria</th>
                    <th class="text-center">Tipo</th>
                    <th class="text-center">Talle</th>
                    <th class="text-center">Precio</th>
                    <th class="text-center">Color</th>
                    <th class="text-center">Stock</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($list as $task) { ?>      
                    <tr>
                        <td class="text-center"><?php echo $task->IDProducto; ?></td>
                        <td class="text-center"><?php echo $task->IDCategoria; ?></td>
                        <td class="text-center"><?php echo $task->Tipo; ?></td>
                        <td class="text-center"><?php echo $task->Talle; ?></td>
                        <td class="text-center"><?php echo $task->Precio; ?></td>
                        <td class="text-center"><?php echo $task->Color; ?></td>
                        <td class="text-center"><?php echo $task->Stock; ?></td>
                        <td class="text-center"><a href="listar" class="btn btn-primary">Volver</a></td>
                    </tr>      
                <?php } ?>
            </tbody>
        </table>

        <?php
        require 'templates/pag/footer.phtml';
    