<?php
        require 'templates/pag/header.phtml';        
        ?>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="text-center">Categoria</th>
                    <th class="text-center">Descripcion</th>
                    <th class="text-center">Marca</th>
                    <th class="text-center">Material</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($categorias as $producto) { ?>      
                    <tr>
                        <td class="text-center"><?php echo $producto->Categoria; ?></td>
                        <td class="text-center"><?php echo $producto->Descripcion; ?></td>
                        <td class="text-center"><?php echo $producto->Marca; ?></td>
                        <td class="text-center"><?php echo $producto->Material; ?></td>
                        <td class="text-center"><a href="categId/<?= $producto->IDCategoria;?>" class="btn btn-primary">Ver Productos</a>
                            <?php if ($admin) { ?>
                            <a href="borrarCateg/<?= $producto->IDCategoria; ?>" type="button" class='btn btn-danger ml-auto'>Eliminar</a>
                            <a href="formModCateg/<?= $producto->IDCategoria; ?>" type="button" class='btn btn-success ml-auto'>Modificar</a>
                            <?php } ?>
                        </td>
                    </tr>      
                <?php } ?>
            </tbody>
        </table>
        <?php
        require 'templates/pag/footer.phtml';
    