<?php 
    require_once 'templates/header.phtml';  
    ?>
<div class="container">
    <h2>Agregar una categoria</h2>

    <form action="addCategoria" method="POST">

        <div class="form-row col-md-6">
        
            <div class="form-group col-md-6">
                <label for="nombre">Nombre:</label>
                <input type="text" class="form-control" id="nombre" name="nombre">
            </div>

            <div class="form-row">
            <div class="form-group col-md-6">
                <label for="ciudad">Ciudad:</label>
                <input type="text" class="form-control" id="ciudad" name="ciudad">
            </div>

            <div class="form-group col-md-6">
                <label for="direccion">Direccion:</label>
                <input type="number" class="form-control" id="direccion" name="direccion">
            </div>

            <div class="form-group col-md-6">
                <label for="fecha">Fecha:</label>
                <input type="text" class="form-control" id="fecha" name="fecha">
            </div>
            <button type="submit" class="btn btn-primary">Agregar</button>
        </div>
        
    </form>
</div>

</body>
</html>
