<?php 
    require_once 'templates/header.phtml';  
    ?>
<div class="container">
    <h2>Agregar un item</h2>
    <form action="addItems" method="POST">
        <div class="form-row col-md-6">
            <div class="form-group col-md-6">
                <label for="tipo">IDCategoria</label>
                <input type="text" class="form-control" id="categoria" name="categoria">
            </div>
        
            <div class="form-group col-md-6">
                <label for="tipo">Tipo:</label>
                <input type="text" class="form-control" id="tipo" name="tipo">
            </div>

            <div class="form-row">
            <div class="form-group col-md-6">
                <label for="talle">Talle:</label>
                <input type="text" class="form-control" id="talle" name="talle">
            </div>

            <div class="form-group col-md-6">
                <label for="precio">Precio:</label>
                <input type="number" class="form-control" id="precio" name="precio">
            </div>

            <div class="form-group col-md-6">
                <label for="precio">Color:</label>
                <input type="text" class="form-control" id="color" name="color">
            </div>

            <div class="form-group col-md-6">
                <label for="precio">Stock:</label>
                <input type="text" class="form-control" id="stock" name="stock">
            </div>

            <button type="submit" class="btn btn-primary">Agregar</button>
        </div>
        
    </form>
</div>

</body>
</html>
