<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>TUDAI - TP Especial</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd;">
        <!-- Navbar content -->
        <a class="navbar-brand" href="listar">
        <img src="./img/logo.jpeg" alt="logo" width= "80px">
        </a>
    <div class="container-fluid" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="listar">Listado <span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="categoria">Productos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="agregar">Agregar items</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="listAdmin">Gestion lista</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="formCategoria">Agregar categorias</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="categoryAdmin">Gestion categorias</a>
        </li>

        <?php if (!isset($_SESSION['USER_ID'])) : ?>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="login">Login</a>
                </li>
                    <?php else : ?>
                <li class="nav-item">
                <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_EMAIL'] ?>)</a>
                </li>
                <?php endif ?>
    </nav>
</body>