<?php
        require 'templates/header.phtml';        
        ?>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Fecha</th>
                    <th>Especificaciones</th>
                    <th>Estado</th>
                    <th>Precio</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($productos as $producto) { ?>      
                    <tr>
                    <td><a href="categoriaId?id=<?php $producto->IDProducto; ?>"><?php echo $producto->Producto; ?></a></td>

                        <td><?php echo $producto->Fecha; ?></td>
                        <td><?php echo $producto->Especificaciones; ?></td>
                        <td><?php echo $producto->Estado; ?></td>
                        <td><?php echo $producto->Precio; ?></td>
                    </tr>      
                <?php } ?>
            </tbody>
        </table>
        <p class="mt-3"><small>Mostrando <?=$count?> productos</small></p>
        <?php
        require 'templates/footer.phtml';
    