<?php
        require 'templates/header.phtml';        
        ?>    
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>IDCategoria</th>
                    <th>Tipo</th>
                    <th>Talle</th>
                    <th>Precio</th>
                    <th>Color</th>
                    <th>Stock</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($ListT as $task) { ?>      
                    <tr>
                        <td><?php echo $task->IDProducto; ?></td>
                        <td><?php echo $task->Tipo; ?></td>
                        <td><?php echo $task->Talle; ?></td>
                        <td><?php echo $task->Precio; ?></td>
                        <td><?php echo $task->Color; ?></td>
                        <td><?php echo $task->Stock; ?></td>
                        <td><a href="listar" class="btn btn-primary">Volver</a></td>
                    </tr>      
                <?php } ?>
            </tbody>
        </table>

        <?php
        require 'templates/footer.phtml';
    