<?php
        require 'templates/header.phtml';        
        ?>    
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Ciudad</th>
                    <th>Telefono</th>
                    <th>Producto</th>
                    <th>Especificaciones</th>
                    <th>Estado</th>
                    <th>Fecha</th>
                    <th>Precio</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($ListT as $task) { ?>      
                    <tr>
                        <td><?php echo $task->Nombre; ?></td>
                        <td><?php echo $task->Apellido; ?></td>
                        <td><?php echo $task->Ciudad; ?></td>
                        <td><?php echo $task->Telefono; ?></td>
                        <td><?php echo $task->Producto; ?></td>
                        <td><?php echo $task->Especificaciones; ?></td>
                        <td><?php echo $task->Estado; ?></td>
                        <td><?php echo $task->Fecha; ?></td>
                        <td><?php echo $task->Precio; ?></td>
                        <td><a href="listar" class="btn btn-primary">Volver</a></td>
                    </tr>      
                <?php } ?>
            </tbody>
        </table>

        <?php
        require 'templates/footer.phtml';
    