<?php
        require 'templates/header.phtml';        
        ?>
    <form action="buscarCat" method="POST"> 
        <div class="mb-3">
            <label for="categoria" class="form-label">Seleccione un producto:</label>
            <select class="col-md-2 form-select form-select-sm" id="categoria" name="categoria">

                <option value="Remera">Remeras</option>
                <option value="Pantalone">Pantalones</option>
                <option value="Buzo">Buzos</option>
                <option value="Campera">Camperas</option>
                <option value="Zapatilla">Zapatillas</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Ver producto</button>
    </form>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Especificaciones</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($productos as $producto) { ?>      
                    <tr>
                        <td><?php echo $producto->TipoProducto; ?></td>
                        <td><?php echo $producto->Especificaciones; ?></td>
                        <td><?php echo $producto->Cantidad; ?></td>
                        <td><?php echo $producto->Precio; ?></td>
                    </tr>      
                <?php } ?>
            </tbody>
        </table>
        <p class="mt-3"><small>Mostrando <?=$count?> productos</small></p>
        <?php
        require 'templates/footer.phtml';
    