<?php require_once './templates/pag/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="row">
            <div class="col-md-12">
                <label for="email">Email</label>
                <input type="email" placeholder="Email" required class="form-control"name="email" aria-describedby="emailHelp">
            </div>
            <div class="col-md-12">
                <label for="password">Contraseña</label>
                <input type="password" placeholder="Password"required class="form-control"name="password">
                <div id="emailHelp" class="form-text">Mínimo 4 caracteres</div>
            </div>
        </div>

        <?php if ($error) {  ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php } ?>
        
        <button type="submit" class="btn btn-primary mt-3">Ingresar</button>
    </form>
</div>

<?php require_once './templates/pag/footer.phtml' ?>
